[build]
  base = "article-experiment-next"
  command = "npm run build"
  publish = ".next"

[build.environment]
  NEXT_PUBLIC_ANALYTICS_ID = "G-M9XMXCYPQS"  # Replace with your actual Google Analytics ID if needed

[[plugins]]
  package = "@netlify/plugin-nextjs" 